# Copied from https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings

locale: "en-US"
title: "Homepage"
title_separator: "-"
name: "Niket Naidu" # &name is a YAML anchor which can be *referenced later
description: "Generic Programmer"
url: https://coder137.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/" # the subpath of your site, e.g. "/blhttps://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.ymlog"
repository: "coder137/coder137.github.io"

# Comments
comments:
  provider: "facebook"
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid: #
    num_posts: #
    colorscheme: #
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "docs/_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml


author:
    name: "Niket Naidu"
    avatar: /assets/images/logo.jpg
    bio: > # TODO, Update Further
        Embedded Systems Enthusiast
    location: "India"
    email: coder137@gmail.com
    github: coder137
    linkedin: niket-naidu-30090a134

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Add Collections here


# Add posts teaser
teaser: /assets/images/c_image.jpg

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      # permalink: /:title/
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"

# Outputting
## permalink: /:categories/:title/
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
#  - jekyll-relative-links

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Relative links (This doesnt seem to work with minimal-mistakes)
# relative_links:
#   enabled:     true
#   collections: true
